# Generated by Django 6.0.2 on 2026-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp')], default='Telegram', max_length=20, verbose_name="Спосіб зв'язку"),
        ),
        migrations.AlterField(
            model_name='order',
            name='social_handle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ваш нікнейм / Номер'),
        ),
    ]
