# Generated by Django 6.0.2 on 2026-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_size_orderitem_size_productimage_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Місто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ref міста'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.CharField(default='', max_length=255, verbose_name='Відділення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse_ref',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ref відділення'),
        ),
    ]
