# Generated by Django 6.0.2 on 2026-03-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['type', 'name'], 'verbose_name': 'Розмір', 'verbose_name_plural': 'Розміри'},
        ),
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.CharField(choices=[('shoes', 'Взуття'), ('apparel', 'Одяг')], default='shoes', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram'), ('PHONE', 'Дзвінок по телефону')], default='TELEGRAM', max_length=20, verbose_name="Спосіб зв'язку"),
        ),
    ]
