# Generated by Django 6.0.2 on 2026-03-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_name_cs_category_name_en_category_name_uk_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['type', 'sorting_order', 'name'], 'verbose_name': 'Розмір', 'verbose_name_plural': 'Розміри'},
        ),
        migrations.AddField(
            model_name='size',
            name='sorting_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортування'),
        ),
    ]
