# Generated by Django 6.0.2 on 2026-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_method',
            field=models.CharField(choices=[('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram'), ('WHATSAPP', 'WhatsApp')], default='TELEGRAM', max_length=20, verbose_name="Спосіб зв'язку"),
        ),
    ]
