# Generated by Django 6.0.2 on 2026-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_coupon_options_coupon_user_profile_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Перегляди'),
        ),
    ]
