# Generated by Django 6.0.2 on 2026-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=10, verbose_name='Telegram Link Token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Created At'),
        ),
    ]
