import os
import re

en_translations = {
    "@username або посилання": "@username or link",
    "Article/SKU": "Article/SKU",
    "Czech": "Czech",
    "Email (для підтвердження)": "Email (for confirmation)",
    "Email": "Email",
    "Email:": "Email:",
    "English": "English",
    "Premium Shop - Твій Стиль": "Premium Shop - Your Style",
    "Ref відділення": "Warehouse Ref",
    "Ref міста": "City Ref",
    "Ukrainian": "Ukrainian",
    "Username:": "Username:",
    "Ім'я занадто коротке": "First name is too short",
    "Ім'я": "First Name",
    "Історія замовлень": "Order History",
    "Адреса:": "Address:",
    "Арт:": "SKU:",
    "Артикул:": "Article:",
    "Бажаєте додати в кошик? 😉": "Want to add to cart? 😉",
    "Будь ласка, вкажіть місто": "Please indicate the city",
    "Будь ласка, оберіть відділення": "Please select a warehouse",
    "Будь ласка, оберіть розмір!": "Please select a size!",
    "В наявності": "In stock",
    "В обробці": "Processing",
    "Ваш відгук...": "Your review...",
    "Ваш коментар": "Your comments",
    "Ваш кошик порожній.": "Your cart is empty.",
    "Ваш кошик": "Your cart",
    "Ваш нікнейм / Номер": "Your nickname / Number",
    "Ваш нікнейм або номер (ми напишемо вам сюди)": "Your nickname or number (we'll text you here)",
    "Ваша оцінка": "Your rating",
    "Ваші дані": "Your details",
    "Введіть коректний номер телефону (напр. +380...)": "Enter a valid phone number (e.g. +380...)",
    "Вже є аккаунт?": "Already have an account?",
    "Взуття": "Shoes",
    "Видалити": "Delete",
    "Вийти": "Logout",
    "Виконано": "Completed",
    "Виникли питання? Напишіть нам у підтримку.": "Questions? Contact our support.",
    "Вкажіть вашу пошту (для відновлення пароля)": "Enter your email (for password recovery)",
    "Всі права захищені.": "All rights reserved.",
    "Всі товари": "All products",
    "Вхід у кабінет": "Account login",
    "Вхід": "Login",
    "Від 8 символів": "8+ characters",
    "Від": "From",
    "Відгук від": "Review by",
    "Відгук": "Review",
    "Відгуки наших клієнтів - PREMIUM SHOP": "Customer reviews - PREMIUM SHOP",
    "Відгуки покупців": "Customer reviews",
    "Відгуки": "Reviews",
    "Відгуків поки немає. Будьте першим!": "No reviews yet. Be the first!",
    "Відділення Нової Пошти": "Nova Poshta Warehouse",
    "Відділення": "Warehouse",
    "Відділення:": "Warehouse:",
    "Відправлено": "Shipped",
    "Вітаємо,": "Welcome,",
    "Графік:": "Schedule:",
    "Дата": "Date",
    "Де нас знайти:": "Where to find us:",
    "Деталі доставки:": "Delivery details:",
    "Дзвінок по телефону": "Phone call",
    "Для того, щоб залишити відгук, будь ласка,": "To leave a review, please",
    "До каталогу": "To catalog",
    "До": "To",
    "Додати в кошик": "Add to cart",
    "Доступні розміри": "Available sizes",
    "Дякуємо за замовлення!": "Thank you for your order!",
    "Дія": "Action",
    "З НАМИ": "WITH US",
    "ЗВ'ЯЖІТЬСЯ": "CONTACT",
    "Залишити відгук": "Leave a review",
    "Замовлення #": "Order #",
    "Замовлення підтверджено!": "Order confirmed!",
    "Замовлення": "Orders",
    "Зареєструватися": "Sign up",
    "Знайди свій ідеальний стиль сьогодні": "Find your perfect style today",
    "Зображення товару": "Product image",
    "Зображення товарів": "Product images",
    "КАЖУТЬ": "SAY",
    "Кабінет": "Dashboard",
    "Каталог одягу та кросівок": "Clothing and sneakers catalog",
    "Категорія": "Category",
    "Категорії": "Categories",
    "Коментар": "Comment",
    "Контакти - PREMIUM SHOP": "Contacts - PREMIUM SHOP",
    "Контакти": "Contacts",
    "Користувач": "User",
    "Купувати зараз": "Shop now",
    "Кількість": "Quantity",
    "Ласкаво просимо | PREMIUM SHOP": "Welcome | PREMIUM SHOP",
    "Логін або Email": "Login or Email",
    "Літери": "Letters",
    "Ми в соцмережах": "We are on social media",
    "Ми завжди на зв'язку тут:": "We're always in touch here:",
    "Ми цінуємо кожного клієнта та ваш фідбек": "We value every customer and your feedback",
    "Мій кабінет": "My dashboard",
    "Місто доставки": "Delivery city",
    "Місто": "City",
    "Місто:": "City:",
    "Навігація": "Navigation",
    "Найкращий вибір преміального одягу та взуття.": "The best selection of premium clothing and footwear.",
    "Наприклад: @nickname або номер телефону для WhatsApp": "Example: @nickname or phone number for WhatsApp",
    "Наш офіс": "Our office",
    "Наші цінності:": "Our values:",
    "Наявність": "Availability",
    "Немає аккаунту?": "No account?",
    "Немає в наявності": "Out of stock",
    "Немає зображення": "No image",
    "Нова Колекція 2026": "New Collection 2026",
    "Нове": "New",
    "Номер телефону": "Phone number",
    "Нікнейм": "Nickname",
    "Оберіть розмір": "Select size",
    "Одяг": "Clothing",
    "Олександр": "Alexander",
    "Оновлено": "Updated",
    "Опис": "Description",
    "Оплачено": "Paid",
    "Отримувач:": "Recipient:",
    "Оформити замовлення": "Checkout",
    "Оформлення замовлення": "Order checkout",
    "Пароль": "Password",
    "Перейти до покупок": "Go shopping",
    "Пн-Пт 10:00 - 19:00": "Mon-Fri 10:00 - 19:00",
    "Повернутися до каталогу": "Return to catalog",
    "Почати шопінг": "Start shopping",
    "Почніть вводити місто...": "Start typing city...",
    "Пошук...": "Search...",
    "Про нас - PREMIUM SHOP": "About us - PREMIUM SHOP",
    "Про нас": "About us",
    "Програма лояльності": "Loyalty program",
    "Продовжити покупки": "Continue shopping",
    "Продовжити як гість": "Continue as guest",
    "Профіль": "Profile",
    "Прізвище занадто коротке": "Last name is too short",
    "Прізвище": "Last name",
    "Підтвердити замовлення": "Confirm order",
    "Разом:": "Total:",
    "Рейтинг": "Rating",
    "Реєстрація": "Registration",
    "Розмір": "Size",
    "Розмір:": "Size:",
    "Розміри": "Sizes",
    "Скасовано": "Cancelled",
    "Сортування": "Sorting",
    "Соцмережі": "Social media",
    "Спосіб зв'язку": "Contact method",
    "Статус": "Status",
    "Створено": "Created",
    "Створити аккаунт": "Create account",
    "Стиль понад усе": "Style above all",
    "Твій стиль починається тут": "Your style begins here",
    "Телефон": "Phone",
    "Телефон:": "Phone:",
    "Тип": "Type",
    "Товар": "Product",
    "Товари": "Products",
    "Товарів не знайдено за вашими критеріями.": "No products found for your criteria.",
    "Тільки оригінал": "Only original",
    "Тільки оригінальна якість": "Only original quality",
    "У вас поки немає замовлень.": "You have no orders yet.",
    "Увійти до кабінету": "Log into your account",
    "Увійти": "Log in",
    "Усього": "Total",
    "Цифри": "Numbers",
    "Ціна (грн)": "Price (UAH)",
    "Ціна": "Price",
    "Швидка доставка": "Fast delivery",
    "Швидкий сервіс": "Fast service",
    "Шевченко": "Shevchenko",
    "ЩО ПРО НАС": "WHAT THEY",
    "Як з вами зручніше зв'язатися?": "How would you like us to contact you?",
    "або": "or",
    "відгуків": "reviews",
    "грн": "UAH",
    "зареєструйтесь": "sign up",
    "кросівки, стрітвір, одяг, Україна, купити кросівки, premium shop": "sneakers, streetwear, clothing, Ukraine, buy sneakers, premium shop",
    "м. Київ, вул. Хрещатик, 1": "Kyiv, Khreshchatyk st., 1",
    "ми завжди в курсі останніх трендів.": "we're always up to date with the latest trends.",
    "на": "on",
    "ніяких компромісів.": "no compromises.",
    "шт.": "pcs.",
    "Ми — команда фанатів вуличної моди, які вірять, що одяг — це не просто речі, а спосіб самовираження. Ми ретельно відбираємо кожну модель кросівок та худі, щоб ви отримували лише найкращу якість та найсвіжіші релізи.": "We are a team of streetwear fans who believe that clothing is not just things, but a way of self-expression. We carefully select every sneaker model and hoodie so that you get only the best quality and the freshest releases.",
    "Будь ласка, перевірте правильність заповнення полів. Деякі дані потребують вашої уваги.": "Please check the correctness of the completed fields. Some data requires your attention.",
    "Дані для доставки підтягуються автоматично з ваших попередніх замовлень.": "Delivery data is pulled automatically from your previous orders.",
    "Ексклюзивні колекції преміального одягу та взуття від провідних брендів світу.": "Exclusive collections of premium clothing and footwear from world-leading brands.",
    "Надійний пароль містить:": "A strong password contains:",
    "Спецсимвол (наприклад !@#$%&)": "Special character (e.g. !@#$%&)",
    "Тут поки порожньо. Станьте першим, хто залишить відгук на один із наших товарів!": "It's empty here for now. Be the first to leave a review on one of our products!",
    "Завантаження відділень...": "Loading warehouses...",
}

cs_translations = {
    "@username або посилання": "@username nebo odkaz",
    "Article/SKU": "Article/SKU",
    "Czech": "Čeština",
    "Email (для підтвердження)": "E-mail (pro potvrzení)",
    "Email": "E-mail",
    "Email:": "E-mail:",
    "English": "Angličtina",
    "Premium Shop - Твій Стиль": "Premium Shop - Váš styl",
    "Ref відділення": "Sklad Ref",
    "Ref міста": "Město Ref",
    "Ukrainian": "Ukrajinština",
    "Username:": "Uživatelské jméno:",
    "Ім'я занадто коротке": "Jméno je příliš krátké",
    "Ім'я": "Jméno",
    "Історія замовлень": "Historie objednávek",
    "Адреса:": "Adresa:",
    "Арт:": "SKU:",
    "Артикул:": "Katalogové číslo:",
    "Бажаєте додати в кошик? 😉": "Chcete přidat do košíku? 😉",
    "Будь ласка, вкажіть місто": "Uveďte prosím město",
    "Будь ласка, оберіть відділення": "Vyberte prosím pobočku",
    "Будь ласка, оберіть розмір!": "Vyberte prosím velikost!",
    "В наявності": "Skladem",
    "В обробці": "Zpracovává se",
    "Ваш відгук...": "Vaše recenze...",
    "Ваш коментар": "Váš komentář",
    "Ваш кошик порожній.": "Váš košík je prázdný.",
    "Ваш кошик": "Váš košík",
    "Ваш нікнейм / Номер": "Vaše přezdívka / Číslo",
    "Ваш нікнейм або номер (ми напишемо вам сюди)": "Vaše přezdívka nebo číslo (sem vám napíšeme)",
    "Ваша оцінка": "Vaše hodnocení",
    "Ваші дані": "Vaše údaje",
    "Введіть коректний номер телефону (напр. +380...)": "Zadejte platné telefonní číslo",
    "Вже є аккаунт?": "Již máte účet?",
    "Взуття": "Obuv",
    "Видалити": "Smazat",
    "Вийти": "Odhlásit se",
    "Виконано": "Dokončeno",
    "Виникли питання? Напишіть нам у підтримку.": "Máte dotazy? Kontaktujte naši podporu.",
    "Вкажіть вашу пошту (для відновлення пароля)": "Zadejte svůj e-mail (pro obnovu hesla)",
    "Всі права захищені.": "Všechna práva vyhrazena.",
    "Всі товари": "Všechny produkty",
    "Вхід у кабінет": "Přihlášení k účtu",
    "Вхід": "Přihlášení",
    "Від 8 символів": "8+ znaků",
    "Від": "Od",
    "Відгук від": "Recenze od",
    "Відгук": "Recenze",
    "Відгуки наших клієнтів - PREMIUM SHOP": "Hodnocení zákazníků - PREMIUM SHOP",
    "Відгуки покупців": "Hodnocení zákazníků",
    "Відгуки": "Recenze",
    "Відгуків поки немає. Будьте першим!": "Zatím žádné recenze. Buďte první!",
    "Відділення Нової Пошти": "Pobočka Nova Poshta",
    "Відділення": "Pobočka",
    "Відділення:": "Pobočka:",
    "Відправлено": "Odesláno",
    "Вітаємо,": "Vítejte,",
    "Графік:": "Otevírací doba:",
    "Дата": "Datum",
    "Де нас знайти:": "Kde nás najdete:",
    "Деталі доставки:": "Detaily doručení:",
    "Дзвінок по телефону": "Telefonní hovor",
    "Для того, щоб залишити відгук, будь ласка,": "Chcete-li zanechat recenzi, prosím",
    "До каталогу": "Do katalogu",
    "До": "Do",
    "Додати в кошик": "Přidat do košíku",
    "Доступні розміри": "Dostupné velikosti",
    "Дякуємо за замовлення!": "Děkujeme za vaši objednávku!",
    "Дія": "Akce",
    "З НАМИ": "S NÁMI",
    "ЗВ'ЯЖІТЬСЯ": "KONTAKTUJTE NÁS",
    "Залишити відгук": "Zanechat recenzi",
    "Замовлення #": "Objednávka #",
    "Замовлення підтверджено!": "Objednávka potvrzena!",
    "Замовлення": "Objednávky",
    "Зареєструватися": "Zaregistrovat se",
    "Знайди свій ідеальний стиль сьогодні": "Najděte svůj dokonalý styl dnes",
    "Зображення товару": "Obrázek produktu",
    "Зображення товарів": "Obrázky produktů",
    "КАЖУТЬ": "ŘÍКАJÍ",
    "Кабінет": "Účet",
    "Каталог одягу та кросівок": "Katalog oblečení a tenisek",
    "Категорія": "Kategorie",
    "Категорії": "Kategorie",
    "Коментар": "Komentář",
    "Контакти - PREMIUM SHOP": "Kontakty - PREMIUM SHOP",
    "Контакти": "Kontakty",
    "Користувач": "Uživatel",
    "Купувати зараз": "Nakupovat nyní",
    "Кількість": "Množství",
    "Ласкаво просимо | PREMIUM SHOP": "Vítejte | PREMIUM SHOP",
    "Логін або Email": "Přihlašovací jméno nebo e-mail",
    "Літери": "Písmena",
    "Ми в соцмережах": "Jsme na sociálních sítích",
    "Ми завжди на зв'язку тут:": "Jsme tu pro vás:",
    "Ми цінуємо кожного клієнта та ваш фідбек": "Vážíme si každého zákazníka a vaší zpětné vazby",
    "Мій кабінет": "Můj účet",
    "Місто доставки": "Město doručení",
    "Місто": "Město",
    "Місто:": "Město:",
    "Навігація": "Navigace",
    "Найкращий вибір преміального одягу та взуття.": "Nejlepší výběr prémiového oblečení a obuvi.",
    "Наприклад: @nickname або номер телефону для WhatsApp": "Například: @nickname nebo telefonní číslo pro WhatsApp",
    "Наш офіс": "Naše kancelář",
    "Наші цінності:": "Naše hodnoty:",
    "Наявність": "Dostupnost",
    "Немає аккаунту?": "Nemáte účet?",
    "Немає в наявності": "Není skladem",
    "Немає зображення": "Žádný obrázek",
    "Нова Колекція 2026": "Nová kolekce 2026",
    "Нове": "Nové",
    "Номер телефону": "Telefonní číslo",
    "Нікнейм": "Přezdívka",
    "Оберіть розмір": "Vyberte velikost",
    "Одяг": "Oblečení",
    "Олександр": "Alexander",
    "Оновлено": "Aktualizováno",
    "Опис": "Popis",
    "Оплачено": "Zaplaceno",
    "Отримувач:": "Příjemce:",
    "Оформити замовлення": "Pokladna",
    "Оформлення замовлення": "Zpracování objednávky",
    "Пароль": "Heslo",
    "Перейти до покупок": "Přejít k nakupování",
    "Пн-Пт 10:00 - 19:00": "Po-Pá 10:00 - 19:00",
    "Повернутися до каталогу": "Návrat do katalogu",
    "Почати шопінг": "Začít nakupovat",
    "Почніть вводити місто...": "Začněte psát město...",
    "Пошук...": "Hledat...",
    "Про нас - PREMIUM SHOP": "O nás - PREMIUM SHOP",
    "Про нас": "O nás",
    "Програма лояльності": "Věrnostní program",
    "Продовжити покупки": "Pokračovat v nákupu",
    "Продовжити як гість": "Pokračovat jako host",
    "Профіль": "Profil",
    "Прізвище занадто коротке": "Příjmení je příliš krátké",
    "Прізвище": "Příjmení",
    "Підтвердити замовлення": "Potvrdit objednávku",
    "Разом:": "Celkem:",
    "Рейтинг": "Hodnocení",
    "Реєстрація": "Registrace",
    "Розмір": "Velikost",
    "Розмір:": "Velikost:",
    "Розміри": "Velikosti",
    "Скасовано": "Zrušeno",
    "Сортування": "Třídění",
    "Соцмережі": "Sociální sítě",
    "Спосіб зв'язку": "Způsob kontaktu",
    "Статус": "Stav",
    "Створено": "Vytvořeno",
    "Створити аккаунт": "Vytvořit účet",
    "Стиль понад усе": "Styl především",
    "Твій стиль починається тут": "Váš styl začíná zde",
    "Телефон": "Telefon",
    "Телефон:": "Telefon:",
    "Тип": "Typ",
    "Товар": "Produkt",
    "Товари": "Produkty",
    "Товарів не знайдено за вашими критеріями.": "Pro vaše kritéria nebyly nalezeny žádné produkty.",
    "Тільки оригінал": "Pouze originál",
    "Тільки оригінальна якість": "Pouze originální kvalita",
    "У вас поки немає замовлень.": "Zatím nemáte žádné objednávky.",
    "Увійти до кабінету": "Přihlásit se k účtu",
    "Увійти": "Přihlásit se",
    "Усього": "Celkem",
    "Цифри": "Číslice",
    "Ціна (грн)": "Cena (UAH)",
    "Ціна": "Cena",
    "Швидка доставка": "Rychlé doručení",
    "Швидкий сервіс": "Rychlý servis",
    "Шевченко": "Ševčenko",
    "ЩО ПРО НАС": "CO O NÁS",
    "Як з вами зручніше зв'язатися?": "Jak vás máme kontaktovat?",
    "або": "nebo",
    "відгуків": "recenzí",
    "грн": "UAH",
    "зареєструйтесь": "zaregistrujte se",
    "кросівки, стрітвір, одяг, Україна, купити кросівки, premium shop": "tenisky, streetwear, oblečení, Ukrajina, koupit tenisky, premium shop",
    "м. Київ, вул. Хрещатик, 1": "Kyjev, ul. Chresčatyk, 1",
    "ми завжди в курсі останніх трендів.": "jsme vždy informováni o nejnovějších trendech.",
    "на": "na",
    "ніяких компромісів.": "žádné kompromisy.",
    "шт.": "ks.",
    "Ми — команда фанатів вуличної моди, які вірять, що одяг — це не просто речі, а спосіб самовираження. Ми ретельно відбираємо кожну модель кросівок та худі, щоб ви отримували лише найкращу якість та найсвіжіші релізи.": "Jsme tým fanoušků streetwear, kteří věří, že oblečení nejsou jen věci, ale způsob sebevyjádření. Pečlivě vybíráme každý model tenisek a mikiny, abyste získali pouze nejlepší kvalitu a nejčerstvější novinky.",
    "Будь ласка, перевірте правильність заповнення полів. Деякі дані потребують вашої уваги.": "Zkontrolujte prosím správnost zadání. Některé údaje vyžadují vaši pozornost.",
    "Дані для доставки підтягуються автоматично з ваших попередніх замовлень.": "Detaily doručení jsou automaticky načteny z vašich předchozích objednávek.",
    "Ексклюзивні колекції преміального одягу та взуття від провідних брендів світу.": "Exkluzivní kolekce prémiového oblečení a obuvi od předních světových značek.",
    "Надійний пароль містить:": "Silné heslo obsahuje:",
    "Спецсимвол (наприклад !@#$%&)": "Speciální znak (např. !@#$%&)",
    "Тут поки порожньо. Станьте першим, хто залишить відгук на один із наших товарів!": "Zatím tu je prázdno. Buďte první, kdo zanechá recenzi na jeden z našich produktů!",
    "Завантаження відділень...": "Načítání poboček...",
}


def translate_po_file(filepath, translations):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    blocks = re.split(r'\n\n+', content)

    new_blocks = []
    for block in blocks:
        if not block.strip():
            continue
        
        # We need a robust extraction since text can span multiple lines.
        msgid = ""
        in_msgid = False
        in_msgstr = False
        
        lines = block.split('\n')
        for line in lines:
            if line.startswith('msgid '):
                in_msgid = True
                in_msgstr = False
                msgid += re.search(r'"(.*)"', line).group(1)
            elif line.startswith('msgstr '):
                in_msgstr = True
                in_msgid = False
            elif line.startswith('"') and in_msgid:
                msgid += re.search(r'"(.*)"', line).group(1)

        # Unescape quotes
        msgid_unescaped = msgid.replace('\\"', '"')
        
        if msgid_unescaped in translations and msgid_unescaped.strip() != "":
            translated = translations[msgid_unescaped]
            # Replace msgstr
            translated_escaped = translated.replace('"', '\\"')
            
            new_lines = []
            is_collecting_msgstr = False
            for line in lines:
                if line.startswith('msgstr '):
                    new_lines.append(f'msgstr "{translated_escaped}"')
                    is_collecting_msgstr = True
                elif line.startswith('"') and is_collecting_msgstr:
                    pass # skip continuing msgstr lines
                else:
                    if line.startswith('msgid '):
                        is_collecting_msgstr = False
                    new_lines.append(line)
            new_blocks.append('\n'.join(new_lines))
        else:
            new_blocks.append(block)

    # Set Charset to UTF-8 in Language header
    result = '\n\n'.join(new_blocks) + '\n'
    result = result.replace('charset=CHARSET', 'charset=UTF-8')
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(result)

print("Translating EN...")
translate_po_file('locale/en/LC_MESSAGES/django.po', en_translations)

print("Translating CS...")
translate_po_file('locale/cs/LC_MESSAGES/django.po', cs_translations)

print("Translating UK...")
translate_po_file('locale/uk/LC_MESSAGES/django.po', {}) # Just fix charset

print("Done.")
